service:
  http_port: 6333
  grpc_port: 6334
  enable_tls: false

storage:
  storage_path: /qdrant/storage
  snapshots_path: /qdrant/snapshots
  on_disk_payload: true
  performance:
    max_search_threads: 0

log_level: INFO
