<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\core\Chishiki.Core\Chishiki.Core.csproj" />
    <ProjectReference Include="..\..\core\Chishiki.Serial.Abstractions\Chishiki.Serial.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\Stubs\*.json" />
  </ItemGroup>

</Project>
