// -----------------------------------------------------------------------------
// File:        ILLMChatClient.cs
// Author:      Piergiorgio Vagnozzi
// Description: Defines the contract for interacting with an LLM provider for chat and completion scenarios.
// Created:     2026-05-10
// Modified:    2026-05-10
// -----------------------------------------------------------------------------
// Copyright (c) Piergiorgio Vagnozzi. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.
// -----------------------------------------------------------------------------

namespace Chishiki.AI.LLM.Abstractions;

/// <summary>Defines the contract for interacting with an LLM provider for chat and completion scenarios.</summary>
public interface ILLMChatClient
{
    /// <summary>Sends a list of messages to the LLM and returns a single aggregated response.</summary>
    /// <param name="messages">The ordered list of messages forming the conversation history.</param>
    /// <param name="options">Optional inference parameters. When <c>null</c> client defaults apply.</param>
    /// <param name="cancellationToken">Token to observe for cancellation.</param>
    /// <returns>The <see cref="LLMChatResponse"/> generated by the model.</returns>
    Task<LLMChatResponse> CompleteAsync(
        IReadOnlyList<LLMChatMessage> messages,
        LLMChatOptions? options = null,
        CancellationToken cancellationToken = default);

    /// <summary>Sends a list of messages to the LLM and streams the response token by token.</summary>
    /// <param name="messages">The ordered list of messages forming the conversation history.</param>
    /// <param name="options">Optional inference parameters. When <c>null</c> client defaults apply.</param>
    /// <param name="cancellationToken">Token to observe for cancellation.</param>
    /// <returns>An async stream of <see cref="LLMStreamingChatChunk"/> instances.</returns>
    IAsyncEnumerable<LLMStreamingChatChunk> CompleteStreamingAsync(
        IReadOnlyList<LLMChatMessage> messages,
        LLMChatOptions? options = null,
        CancellationToken cancellationToken = default);
}
