// -----------------------------------------------------------------------------
// File:        LLMChatRole.cs
// Author:      Piergiorgio Vagnozzi
// Description: Enumerates the roles a participant can have in an LLM chat conversation.
// Created:     2026-05-10
// Modified:    2026-05-10
// -----------------------------------------------------------------------------
// Copyright (c) Piergiorgio Vagnozzi. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.
// -----------------------------------------------------------------------------

namespace Chishiki.AI.LLM.Abstractions;

/// <summary>Enumerates the roles a participant can have in an LLM chat conversation.</summary>
public enum LLMChatRole
{
    /// <summary>The system role used to provide model instructions and context.</summary>
    System,

    /// <summary>The user role representing messages sent by the end user.</summary>
    User,

    /// <summary>The assistant role representing messages generated by the LLM.</summary>
    Assistant,

    /// <summary>The tool role representing output returned by a tool or function call.</summary>
    Tool,
}
