// -----------------------------------------------------------------------------
// File:        LLMTokenUsage.cs
// Author:      Piergiorgio Vagnozzi
// Description: Represents token consumption metadata returned by an LLM provider.
// Created:     2026-05-10
// Modified:    2026-05-10
// -----------------------------------------------------------------------------
// Copyright (c) Piergiorgio Vagnozzi. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.
// -----------------------------------------------------------------------------

namespace Chishiki.AI.LLM.Abstractions;

/// <summary>Represents token consumption metadata returned by an LLM provider.</summary>
/// <param name="PromptTokens">Number of tokens consumed by the input prompt.</param>
/// <param name="CompletionTokens">Number of tokens generated by the model.</param>
/// <param name="TotalTokens">Total tokens used for the request (prompt + completion).</param>
public sealed record LLMTokenUsage(int PromptTokens, int CompletionTokens, int TotalTokens);
