<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Orleans.Client" Version="10.0.1" />
    <PackageReference Include="Microsoft.Orleans.Clustering.Redis" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Chishiki.Clustering\Chishiki.Clustering.csproj" />
    <ProjectReference Include="..\..\Chishiki.Hub.Contracts\Chishiki.Hub.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>Chishiki.Clustering.Client.UnitTests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

</Project>
