<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OpenCvSharp4" Version="4.13.0.20260528" />
    <PackageReference Include="OpenCvSharp4.runtime.win" Version="4.13.0.20260528" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\core\Chishiki.Core\Chishiki.Core.csproj" />
    <ProjectReference Include="..\Chishiki.Vision.Abstraction\Chishiki.Vision.Abstraction.csproj" />
    <ProjectReference Include="..\Chishiki.Vision.Common\Chishiki.Vision.Common.csproj" />
  </ItemGroup>

</Project>
