<Project Sdk="Microsoft.NET.Sdk">

 <PropertyGroup>
 <TargetFramework>net10.0</TargetFramework>
 <ImplicitUsings>enable</ImplicitUsings>
 <Nullable>enable</Nullable>
 </PropertyGroup>

 <ItemGroup>
 <ProjectReference Include="..\..\core\Chishiki.Core\Chishiki.Core.csproj" />
 <ProjectReference Include="..\Chishiki.Vision.Abstraction\Chishiki.Vision.Abstraction.csproj" />
 </ItemGroup>

</Project>
