<Project Sdk="Microsoft.NET.Sdk">

 <PropertyGroup>
 <TargetFramework>net10.0</TargetFramework>
 <ImplicitUsings>enable</ImplicitUsings>
 <Nullable>enable</Nullable>
 </PropertyGroup>

 <ItemGroup>
 <ProjectReference Include="..\Chishiki.Core\Chishiki.Core.csproj" />
 <ProjectReference Include="..\Chishiki.Data\Chishiki.Data.csproj" />
 <ProjectReference Include="..\Chishiki.Mapping\Chishiki.Mapping.csproj" />
 </ItemGroup>

</Project>
