<Project Sdk="Microsoft.NET.Sdk">

 <PropertyGroup>
 <TargetFramework>net10.0</TargetFramework>
 <ImplicitUsings>enable</ImplicitUsings>
 <Nullable>enable</Nullable>
 <IsPackable>false</IsPackable>
 </PropertyGroup>

 <ItemGroup>
 <PackageReference Include="Microsoft.NET.Test.Sdk"/>
 <PackageReference Include="NUnit"/>
 <PackageReference Include="NUnit3TestAdapter">
 <PrivateAssets>all</PrivateAssets>
 <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
 </PackageReference>
 <PackageReference Include="coverlet.collector">
 <PrivateAssets>all</PrivateAssets>
 <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
 </PackageReference>
 </ItemGroup>

 <ItemGroup>
 <ProjectReference Include="..\..\src\shared\iot\Chishiki.ESPTool\Chishiki.ESPTool.csproj" />
 <ProjectReference Include="..\..\src\shared\core\Chishiki.Serial.Abstractions\Chishiki.Serial.Abstractions.csproj" />
 </ItemGroup>

</Project>
