<Project Sdk="Microsoft.NET.Sdk">

 <PropertyGroup>
 <TargetFramework>net10.0</TargetFramework>
 <ImplicitUsings>enable</ImplicitUsings>
 <Nullable>enable</Nullable>
 <IsPackable>false</IsPackable>
 </PropertyGroup>

 <ItemGroup>
 <PackageReference Include="Aspire.Hosting.Testing"/>
 <PackageReference Include="MessagePack"/>
 <PackageReference Include="Microsoft.NET.Test.Sdk"/>
 <PackageReference Include="NUnit"/>
 <PackageReference Include="NUnit3TestAdapter">
 <PrivateAssets>all</PrivateAssets>
 <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
 </PackageReference>
 <PackageReference Include="coverlet.collector">
 <PrivateAssets>all</PrivateAssets>
 <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
 </PackageReference>
 </ItemGroup>

 <ItemGroup>
 <ProjectReference Include="..\..\src\infrastructure\aspire\Chishiki.Infrastructure.Aspire.AppHost\Chishiki.Infrastructure.Aspire.AppHost.csproj" />
 </ItemGroup>

</Project>
