<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>e22b4305-1d90-4fdd-990f-5b6d58a999bd</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..\..</DockerfileContext>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.5" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
    <PackageReference Include="NSwag.AspNetCore" Version="14.6.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\infrastructure\aspire\Chishiki.Infrastructure.Aspire.ServiceDefaults\Chishiki.Infrastructure.Aspire.ServiceDefaults.csproj" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>Chishiki.API.Web.UnitTests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

</Project>
