// -----------------------------------------------------------------------------
// File:        DetectionResult.cs
// Author:      Piergiorgio Vagnozzi
// Description: Holds the result of a single motion detection pass on a video frame.
// Created:     2025-01-01
// Modified:    2026-05-31
// -----------------------------------------------------------------------------
// Copyright (c) Piergiorgio Vagnozzi. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.
// -----------------------------------------------------------------------------

namespace Chishiki.Vision.Abstraction.Detectors;

/// <summary>Holds the result of a single motion detection analysis on a video frame.</summary>
public record DetectionResult<TDetection>
    where TDetection : Detection
{
    /// <summary>
    /// Initializes a new instance of the <see cref="DetectionResult{TDetection}"/> record with the specified original frame, annotated frame, detected regions, and an optional timestamp. This constructor allows for the creation of a fully populated detection result object, ensuring that all necessary data is provided at the time of instantiation. The original frame represents the unmodified image captured from the video source, while the annotated frame contains visual highlights of the detected motion regions. The detections collection holds the details of each detected region, and the timestamp indicates when the frame was captured, providing crucial temporal context for analysis and synchronization with other data sources.
    /// </summary>
    /// <param name="originalFrame">The original captured frame.</param>
    /// <param name="annotatedFrame">The frame with motion regions drawn as highlighted rectangles.</param>
    /// <param name="detections">The collection of detected regions.</param>
    /// <param name="timestamp">The UTC timestamp when the frame was captured.</param>
    public DetectionResult(
        IImage originalFrame,
        IImage? annotatedFrame = null,
        IEnumerable<TDetection>? detections = null,
        DateTimeOffset? timestamp = null)
    {
        OriginalFrame = originalFrame;
        AnnotatedFrame = annotatedFrame ?? originalFrame;
        Detections = detections is not null ? detections.ToList().AsReadOnly() : Array.Empty<TDetection>();
        Timestamp = timestamp ?? DateTimeOffset.UtcNow;
    }

    /// <summary>
    /// Gets the original captured frame. This property holds the unmodified image data as it was captured from the video source, without any annotations or processing applied. The original frame is essential for reference and further analysis, allowing users to compare it with the annotated frame to understand the context of the detected motion regions. It may also be used for archival purposes or for applying different detection algorithms in the future without needing to re-capture the frame.
    /// </summary>
    public IImage OriginalFrame { get; init; }

    /// <summary>
    /// Gets the frame with motion regions drawn as highlighted rectangles. This annotated frame is generated by the detector after processing the original frame and applying the detection algorithm. It visually represents the detected motion areas, allowing for easy identification of where motion was detected within the frame. The annotated frame is typically used for display purposes or for saving to disk, while the original frame may be retained for further analysis or archival.
    /// </summary>
    public IImage AnnotatedFrame { get; init; }

    /// <summary>
    /// Gets the collection of detected regions. Each item in this collection represents a distinct area within the frame where motion was detected, typically defined by a bounding rectangle and associated metadata such as area or confidence score. The collection is read-only to ensure that the integrity of the detection results is maintained after they are generated by the detector.
    /// </summary>
    public IReadOnlyList<TDetection> Detections { get; init; }

    /// <summary>
    /// Gets the UTC timestamp when the frame was captured. This timestamp is crucial for synchronizing detections with other data sources, such as logs or external events, and for analyzing temporal patterns in the detected motion. By default, it is set to the current UTC time at the moment of instantiation, but it can be overridden if the capture time is known from an external source.
    /// </summary>
    public DateTimeOffset Timestamp { get; init; }
}

/// <summary>
/// Detects motion in video frames and produces a <see cref="DetectionResult{TDetection}"/> containing the original frame, annotated frame, detected regions, and timestamp. This extension method provides a convenient factory for creating detection results with all necessary components initialized, streamlining the process of generating consistent and well-formed detection results across different detectors and use cases.
/// </summary>
public static class DetectionResultExtensions
{
    /// <summary>
    /// Creates a new instance of <see cref="DetectionResult{TDetection}"/> with the provided original frame, annotated frame, detections, and an optional timestamp. This factory method simplifies the instantiation of detection results by allowing callers to provide all necessary components in a single call, ensuring that the resulting object is properly initialized with all required data. If the timestamp is not provided, it defaults to the current UTC time, ensuring that every detection result has a valid timestamp for synchronization and analysis purposes.
    /// </summary>
    /// <typeparam name="TResult">Result type</typeparam>
    /// <typeparam name="TDetection">Detection type</typeparam>
    /// <param name="originalFrame">The original captured frame.</param>
    /// <param name="annotatedFrame">The frame with motion regions highlighted.</param>
    /// <param name="detections">The collection of detected regions.</param>
    /// <param name="timestamp">The UTC timestamp when the frame was captured.</param>
    /// <returns></returns>
    public static TResult Create<TResult, TDetection>(
        this IImage originalFrame,
        IImage? annotatedFrame,
        IEnumerable<TDetection> detections,
        DateTimeOffset? timestamp = null)
        where TResult : DetectionResult<TDetection>, new()
        where TDetection : Detection =>
        new()
        {
            OriginalFrame = originalFrame,
            AnnotatedFrame = annotatedFrame ?? originalFrame,
            Detections = detections.ToList().AsReadOnly(),
            Timestamp = timestamp ?? DateTimeOffset.UtcNow
        };
}
